server:
  port: 8002

# 应用名(微服务名)
spring:
  application:
    name: microservice-example

eureka:
  instance:
    # 是否注册到eureka server
    prefer-ip-address: true
    # 主机名
    hostname: microservice-example2
  client:
    service-url:
      # eureka server的地址
      defaultZone: http://user:123456@localhost:8761/eureka,http://localhost:8762/eureka

# 通过info.*添加公开的应用信息
info:
  app:
    name: microservice-example2
    encoding: utf-8
    java:
      source: 1.8
      target: 1.8

# 开启actuator的refresh端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always